repository:
  # Configurações do repositório
  has_wiki: false
  has_projects: true
  has_downloads: false

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: ["test", "lint", "type-check"]
      enforce_admins: true
      restrictions: null
